version: '3'
services:
  chrome_server:
    build:
      context: ../..
      dockerfile: ./local_dev/docker/chrome_server.dockerfile
    volumes:
      - $PWD/../volumes/log/chrome_server:/log/chrome_server
      - $PWD/../volumes/log/nginx:/log/nginx
      - $PWD/../volumes/tmp:/tmp
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
    container_name: "chrome_server"
    ports:
      - ${SERVER_PORT_MAPPING}
    networks:
      chrome_server_net:
        ipv4_address: 192.18.0.5

networks:
  chrome_server_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.18.0.0/16
